### ISSUE TITLE
System wide Julia packages

### ISSUE THREAD

**Issue by fredrikekre** [mauro3/JupyterHubWithJulia#1]
From the instructions

> To make these packages available to users, those to *.toml files need to be copied to the user’s .julia/environments/v1.4 folder. 
This is done in a subsequent step, see Enable TLJH-wide Julia packages.

This could be simplified by adding a system wide load path entry, similar to your system wide depots. Example:
```
$ global_load_path=$PWD/global-load-path

$ mkdir $global_load_path

$ export JULIA_LOAD_PATH=":$global_load_path" # colon separated list; the initial empty string appends the default load path

$ julia -e 'foreach(println, Base.load_path())'
/home/fredrik/.julia/environments/v1.5/Project.toml
/opt/julia/julia-1.5/share/julia/stdlib/v1.5
/home/fredrik/global-load-path
```
Make sure the example package is not available
```
$ julia -e 'using Crayons'
ERROR: ArgumentError: Package Crayons not found in current path:
- Run `import Pkg; Pkg.add("Crayons")` to install the Crayons package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
```
Install Crayons to the system wide load path entry
```
$ JULIA_LOAD_PATH=${global_load_path}/Project.toml pkg add Crayons
  Resolving package versions...
Updating `~/global-load-path/Project.toml`
  [a8cc5b0e] + Crayons v4.0.4
Updating `~/global-load-path/Manifest.toml`
  [a8cc5b0e] + Crayons v4.0.4
```
make sure it is available now
```
$ julia -e 'using Crayons'
```

**Comment by mauro3** [comment]
Thanks for the comment!  I'll update it.

Ok, so this creates a stacked environment, this is one of my comments in https://github.com/JuliaLang/Pkg.jl/issues/1952 resolved.

**Comment by mauro3** [comment]
Just looking at `?LOAD_PATH` it says " `@name` refers to a named environment, which are stored in depots (see JULIA_DEPOT_PATH) under the environments subdirectory."

Would this mean that if I point the `$julia_global_env` to `$julia_global_depot/environments/v1.4` that this should be picked up directly, i.e. without needing a `$global_load_path`?  I think I tried this but maybe I did something wrong.

**Comment by mauro3** [comment]
Thanks a lot @fredrikekre!  I now updated the script, see https://github.com/mauro3/JupyterHubWithJulia/blob/e2924c29744d148907a900d9335a0d1ea0275c43/tljh_install.sh#L107-L138.

A couple of questions:
- is this documented somewhere?  If not where should I add this?
- What's the reason the Project.toml in `$julia_global_env` is not picked up automatically?

**Comment by fredrikekre** [comment]
> is this documented somewhere? If not where should I add this?

`LOAD_PATH` you mean? https://docs.julialang.org/en/v1/base/constants/#Base.LOAD_PATH and the env var https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_LOAD_PATH

> What's the reason the Project.toml in $julia_global_env is not picked up automatically?

What do you mean? Isn't it?

Btw, I would probably have set `JULIA_LOAD_PATH` for all users instead of configuring their `startup.jl` (is that even sourced by IJulia?) but probably does not really matter.

**Comment by mauro3** [comment]
With "documented", I don't mean `?LOAD_PATH` or some such detail, but "how to install packages system-wide". It's a long stretch from reading about `LOAD_PATH` to being able to install system-wide; at least it was for me (and discussions on discourse seem to suggest others are struggling too.)

> What do you mean? Isn't it?

I mean that the DEPOT_PATH[2] points by default to a system-wide depot.  However, the associated environment `DEPOT_PATH[2]/environments/v#.#` is not loaded by default.  My question is, what is the rational behind this choice.  Especially, as packages can be loaded by default from the other two paths in DEPOT_PATH[[1,3]].

> Btw, I would probably have set JULIA_LOAD_PATH for all users instead of configuring their startup.jl (is that even sourced by IJulia?) but probably does not really matter.

Yes, it gets sourced.  I guess it was motivated by me knowing more about julia variables than environment variables.

**Comment by fredrikekre** [comment]
Okay, no, I have just seen a number of posts on discourse etc about it. I agree it would be good with some more "official" documentation, but this seems highly system dependent so not sure it would fit in the regular manual.

> I mean that the DEPOT_PATH[2] points by default to a system-wide depot. However, the associated environment DEPOT_PATH[2]/environments/v#.# is not loaded by default. My question is, what is the rational behind this choice. Especially, as packages can be loaded by default from the other two paths in DEPOT_PATH[[1,3]].

Haven't really thought about it actually. The reason it is happening is that the default `LOAD_PATH` is 
```julia
julia> LOAD_PATH
3-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
```
so when that is expanded we look through tall depots looking for these. For example, if `DEPOT_PATH[1]/environments/v1.5` does not exist but `DEPOT_PATH[2]/environments/v1.5` does, then it is picked up. Thats why you need https://github.com/mauro3/JupyterHubWithJulia/blob/e2924c29744d148907a900d9335a0d1ea0275c43/tljh_install.sh#L119.

I tried a bit myself, and it might be easier to use a "named"-environment for your global packages instead of using the `v1.4` folder. I found this setup quite neat:
```
$ cat setup 
#!/bin/bash

# Global depot /julia is prepended when setting up
export JULIA_LOAD_PATH="/julia/Project.toml:@stdlib"
export JULIA_DEPOT_PATH="/julia"

# Instantiate the environment we copied
julia -e 'using Pkg; Pkg.instantiate(); Pkg.precompile();'

# Add users
groupadd julia-users
useradd -m -g julia-users julia

# Set global environment variables
echo "export JULIA_DEPOT_PATH=\":/julia\"" >> /etc/profile
echo "export JULIA_LOAD_PATH=\":/julia/Project.toml\"" >> /etc/profile
```

**Comment by fredrikekre** [comment]
> Yes, it gets sourced. I guess it was motivated by me knowing more about julia variables than environment variables.

Yea, might be easier actually.
