### ISSUE TITLE
Permission denied error when adding packages

### ISSUE THREAD

**Issue by sethaxen** [mauro3/JupyterHubWithJulia#3]
As I understand it, these lines set it up so that there's a global environment into which we have installed packages, but the user also has a local environment into which they can install their own packages without modifying the global environment:

https://github.com/mauro3/JupyterHubWithJulia/blob/cd0b6591dbc0dcf45e0fc76760b1b826023e1ef0/tljh_install.sh#L131-L138

However, when a user tries doing 

```julia
using Pkg
Pkg.add("BenchmarkTools")
```
they get the error message

```julia
IOError: stat("/opt/tljh/user/share/julia/site/julia-1.6.0/local/share/julia/registries/General/Registry.toml"): permission denied (EACCES)
```
@mauro3 do you know what this error refers to and how I might be able to resolve it?

**Comment by sethaxen** [comment]
It turns out `/opt/tljh/user/share/julia/site/julia-1.6.0/local/share/julia/registries/General/` had permissions `drwx------`, so it was not readable by all users, hence the error. Perhaps this should be fixed in the installation script?

**Comment by mauro3** [comment]
No, the user should be able to install into their own `~/.julia` directory. From your error, for some reason it tires the global environment instead.

I see that you are using Julia 1.6 but my scripts hard-codes Julia 1.4.  Did you update all of the relevant paths?  (I really should code this properly, see #4)

**Comment by sethaxen** [comment]
> I see that you are using Julia 1.6 but my scripts hard-codes Julia 1.4. Did you update all of the relevant paths? (I really should code this properly, see #4)

I thought I did, but perhaps I missed some. I'll try again and, if it works, submit a PR to fix #4.

**Comment by mauro3** [comment]
Sounds good, thanks.  I'm currently trying the standard 1.4 install and see how that goes.

**Comment by mauro3** [comment]
Ah, I see, now Julia 1.6 gets installed via conda... that sure breaks the script!

If you want, you could just make a PR with the updated script you used and we can take it from there.

**Comment by mauro3** [comment]
Yes, running the install-script I also get that error.

The other possibility would be that something in Julia's Pkg changed which breaks this setup.

**Comment by sethaxen** [comment]
> The other possibility would be that something in Julia's Pkg changed which breaks this setup.

Looking at the changelog, the only thing that looks like it could be relevant is https://github.com/JuliaLang/julia/blob/master/HISTORY.md#command-line-option-changes-1
