### ISSUE TITLE
Refactor installation of Julia

### ISSUE THREAD

**Issue by sethaxen** [mauro3/JupyterHubWithJulia#5]
Currently `tljh_install.sh` does all the work to set up TLJH and then does all the work to set up one Julia version. It would be convenient to factor the latter part into its own bash script `julia_install.sh`, which could then be called by `tljh_install.sh` or also independently by the user multiple times to either reinstall Julia or add additional Julia versions as kernels.

To support multiple Julia versions, we can't rely on the conda channel but rather should install the official binaries. The Julia docs recommend the Python package [jill](https://github.com/johnnychen94/jill.py) as a platform-agnostic way to do so.

**Comment by sethaxen** [comment]
Relates #4

**Comment by mauro3** [comment]
Thanks!  This sounds good. 

Do you think jill is needed?  We're only running on Ubuntu and it's pretty clear where the binary should go.  So maybe just `wget` it?

**Comment by sethaxen** [comment]
> Do you think jill is needed? We're only running on Ubuntu and it's pretty clear where the binary should go. So maybe just `wget` it?

The main reasons to use jill are for the convenient version syntax, e.g. easily install latest stable version, or release candidate, etc. So if we require that the user provides exact version numbers, then it's straightforward to just use `wget`.

**Comment by mauro3** [comment]
> So if we require that the user provides exact version numbers

I think that would be ok.   But if you feel strongly about jill then go for it.

**Comment by mauro3** [comment]
Closed in #6.
